"""
API Documentation Routes
This module contains routes for API documentation and guides.
"""
import os
import logging
from flask import Blueprint, render_template, send_from_directory, redirect, url_for, send_file
from flask_login import login_required, current_user
from io import BytesIO
import tempfile

api_docs_bp = Blueprint('api_docs', __name__, url_prefix='/api-docs')
logger = logging.getLogger(__name__)

@api_docs_bp.route('/')
def index():
    """API documentation index page"""
    return render_template('api_docs/index.html', title='API Documentation')

@api_docs_bp.route('/nvc-api-infrastructure')
def nvc_api_infrastructure():
    """NVC API Infrastructure document page"""
    return render_template('api_docs/nvc_api_infrastructure.html', title='NVC API Infrastructure')

@api_docs_bp.route('/nvc-api-infrastructure.pdf')
def nvc_api_infrastructure_pdf():
    """Serve static PDF version of the NVC API Infrastructure document"""
    try:
        # Serve the static PDF file that was generated by generate_api_pdf.py
        static_file_path = os.path.join(os.getcwd(), 'static', 'documents', 'NVC_API_Infrastructure.pdf')
        
        # If the file doesn't exist, generate it
        if not os.path.exists(static_file_path):
            from generate_api_pdf import generate_api_infrastructure_pdf
            generate_api_infrastructure_pdf()
        
        # Serve the static PDF file
        return send_file(static_file_path, 
                         mimetype='application/pdf', 
                         as_attachment=True, 
                         download_name='NVC_API_Infrastructure.pdf')
    
    except Exception as e:
        logger.error(f"Error serving API Infrastructure PDF: {str(e)}")
        # If we can't serve the PDF for some reason, redirect to the HTML version
        return redirect(url_for('api_docs.nvc_api_infrastructure'))

@api_docs_bp.route('/api-reference')
def api_reference():
    """API reference documentation"""
    return render_template('api_docs/api_reference.html', title='API Reference')

@api_docs_bp.route('/integration-guides')
def integration_guides():
    """API integration guides"""
    return render_template('api_docs/integration_guides.html', title='Integration Guides')